=== jwausle/smarthome/bundles/core/org.eclipse.smarthome.core.thing.xml/thing-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:thing-description="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
        xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
        targetNamespace="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0">

    <xs:import namespace="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
            schemaLocation="http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd"/>

    <xs:element name="thing-descriptions">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="thing-type" type="thing-description:thingType"/>
                <xs:element name="bridge-type" type="thing-description:bridgeType"/>
                <xs:element name="channel-type" type="thing-description:channelType"/>
            </xs:choice>
            <xs:attribute name="bindingId" type="config-description:idRestrictionPattern" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="thingType">
        <xs:sequence>
            <xs:element name="supported-bridge-type-refs" type="thing-description:supportedBridgeTypeRefs" minOccurs="0"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="channels" type="thing-description:channels" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
    </xs:complexType>

    <xs:complexType name="supportedBridgeTypeRefs">
        <xs:sequence>
            <xs:element name="bridge-type-ref" type="thing-description:bridgeTypeRef" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeTypeRef">
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
    </xs:complexType>

    <xs:complexType name="channels">
        <xs:sequence>
            <xs:element name="channel" type="thing-description:channel" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeType">
        <xs:complexContent>
            <xs:extension base="thing-description:thingType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="channel">
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="typeId" type="config-description:idRestrictionPattern" use="required"/>
    </xs:complexType>

    <xs:complexType name="channelType">
        <xs:sequence>
            <xs:element name="item-type" type="xs:string"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:element name="tags" type="thing-description:tags" minOccurs="0"/>
            <xs:element name="state-description" type="thing-description:stateDescription" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="config-description:idRestrictionPattern" use="required"/>
        <xs:attribute name="readOnly" type="xs:boolean" use="optional"/>
    </xs:complexType>

    <xs:complexType name="tags">
        <xs:sequence>
            <xs:element name="tag" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stateDescription">
        <xs:all>
            <xs:element name="range" type="thing-description:range" minOccurs="0"/>
            <xs:element name="step" type="thing-description:step" minOccurs="0"/>
            <xs:element name="format" type="thing-description:format" minOccurs="0"/>
            <xs:element name="states" type="thing-description:states" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="range">
        <xs:attribute name="min" type="xs:decimal" use="required"/>
        <xs:attribute name="max" type="xs:decimal" use="required"/>
    </xs:complexType>

    <xs:complexType name="step">
        <xs:attribute name="size" type="xs:decimal" use="required"/>
    </xs:complexType>

    <xs:complexType name="format">
        <xs:attribute name="pattern" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="states">
        <xs:sequence>
            <xs:element name="state" type="thing-description:state" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="state">
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="label" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== jwausle/smarthome/bundles/core/org.eclipse.smarthome.core.thing.xml.test/src/test/resources/test-bundle-pool/yahooweather.bundle/ESH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="yahooweather"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
        xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <!-- YahooWeather Binding -->
    <thing-type id="weather">
        <label>Weather Information *</label>
        <description>@text/CUSTOM_KEY</description>

		<channels>
			<channel id="temperature" typeId="temperature" />
		</channels>

    </thing-type>

    <channel-type id="temperature">
        <item-type>Number</item-type>
        <label>Temperature</label>
        <description>Current temperature in degrees celsius (metric) or fahrenheit (us)</description>
    </channel-type>

</thing:thing-descriptions>

=== jwausle/smarthome/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LCT003.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="hue"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <!-- Hue Color Spot with GU10 socket (see http://www.everyhue.com/vanilla/discussion/47/model-ids/p1) -->
    <thing-type id="LCT003">
        <supported-bridge-type-refs>
            <bridge-type-ref id="bridge" />
        </supported-bridge-type-refs>

        <label>Hue Bulb GU10</label>
        <description>This is a Philips Hue spot with GU10 socket</description>

        <channels>
            <channel id="color" typeId="color" />
            <channel id="color_temperature" typeId="color_temperature" />
        </channels>

        <config-description>
            <parameter name="lightId" type="text">
                <label>Light ID</label>
                <description>The light identifier identifies one certain hue light.</description>
                <required>true</required>
            </parameter>
        </config-description>
    </thing-type>
</thing:thing-descriptions>

=== jwausle/smarthome/bundles/core/org.eclipse.smarthome.core.thing.xml.test/example/channels.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="hue"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <!-- Color Channel -->
    <channel-type id="color">
        <item-type>Color</item-type>
        <label>Color</label>
        <description>The color channel allows to control the color of a light.
            It is also possible to dim values and switch the light on and off.
        </description>
        <tags>
            <tag>Hue</tag>
            <tag>ColorLamp</tag>
        </tags>

        <config-description>
            <parameter name="lastDimValue" type="boolean" />
        </config-description>
    </channel-type>

    <!-- Brightness Channel -->
    <channel-type id="brightness">
        <item-type>Dimmer</item-type>
        <label>Brightness</label>
        <description>The brightness channel allows to control the brightness of a light.
            It is also possible to switch the light on and off.
        </description>
        <tags>
            <tag>Hue</tag>
            <tag>DimmableLamp</tag>
        </tags>

        <config-description>
            <parameter name="lastDimValue" type="boolean" />
        </config-description>
    </channel-type>

    <!-- Color Temperature Channel -->
    <channel-type id="color_temperature">
        <item-type>Dimmer</item-type>
        <label>Color Temperature</label>
        <description>The color temperature channel allows to set the color
            temperature of a light from 0 (cold) to 100 (warm).</description>
        <tags>
            <tag>Hue</tag>
            <tag>AmbientLamp</tag>
        </tags>
    </channel-type>

    <!-- Alarm Channel -->
    <channel-type id="alarm">
        <item-type>Number</item-type>
        <label>Alarm System</label>
        <description>The light blinks if alarm is set.</description>
        <category>ALARM</category>
        <tags>
            <tag>Hue</tag>
            <tag>AlarmSystem</tag>
        </tags>
        <state-description>
            <range min="0" max="100.0" />
            <step size="10.0" />
            <format pattern="%d Celsius" />
            <states>
                <state value="LIGHT" label="Light" />
                <state value="SOUND" label="Sound" />
            </states>
        </state-description>
    </channel-type>

    <!-- Motion Channel -->
    <channel-type id="motion" readOnly="true">
        <item-type>Number</item-type>
        <label>Motion Sensor</label>
        <description>The sensor detecting motion.</description>
        <category>MOTION</category>
        <tags>
            <tag>Hue</tag>
            <tag>AlarmSystem</tag>
        </tags>
    </channel-type>

    <!-- Alarm System Channel -->
    <channel-group-type id="alarm_system">
        <item-type>Number</item-type>
        <label>Alarm System</label>
        <description>The alarm system.</description>
        <tags>
            <tag>Hue</tag>
            <tag>AlarmSystem</tag>
        </tags>
        <channels>
            <channel id="alarm" typeId="alarm"/>
            <channel id="motion" typeId="motion"/>
        </channels>
    </channel-group-type>

</thing:thing-descriptions>
